volumes:
  react_node_modules:
  postgres_data:

services:

  api:
    container_name: api
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - docstral_network

  frontend:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app:/app
      - react_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=http://localhost:5173
      - VITE_VERSION=local
      - DOCKER=1
    networks:
      - docstral_network

networks:
    docstral_network:
